stages:
  ingest:
    cmd: python -m data_ingestion.ingest
    deps:
    - data_ingestion/ingest.py
    outs:
    - data/processed
  transform:
    cmd: python -m data_cleaning.clean_data
    deps:
      - data_cleaning/clean_data.py
      - data_validation/validate_schema.py
      - data/processed/netflix.parquet
      - data/processed/rotten_tomatoes_summary.parquet
      - data/processed/rotten_tomatoes_review.parquet
    outs:
      - data/transformed/t_netflix.parquet
      - data/transformed/t_rotten_tomatoes_summary.parquet
      - data/transformed/t_rotten_tomatoes_review.parquet

